# Generated by Django 3.2 on 2021-12-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20211208_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelroom',
            name='reserved',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='reserved_from',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='reserved_to',
        ),
        migrations.AddField(
            model_name='bookinginfo',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookinginfo',
            name='reserved_from',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='bookinginfo',
            name='reserved_to',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
