# Generated by Django 3.2 on 2021-12-08 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20211208_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinginfo',
            name='reserved',
        ),
    ]
