# Generated by Django 3.2 on 2021-12-08 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_bookinginfo_reserved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_from', models.DateField(blank=True, default=None, null=True)),
                ('reserved_to', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookinginfo',
            name='reserved_from',
        ),
        migrations.RemoveField(
            model_name='bookinginfo',
            name='reserved_to',
        ),
        migrations.AddField(
            model_name='bookinginfo',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='listings.reservation'),
        ),
    ]
