# Generated by Django 3.2 on 2021-12-08 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20211208_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinginfo',
            name='reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='listings.listing'),
        ),
    ]
