# Generated by Django 3.2 on 2021-12-08 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20211208_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='apartment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='hotel_room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='listings.hotelroom'),
        ),
        migrations.DeleteModel(
            name='Apartment',
        ),
    ]
