# Generated by Django 3.2 on 2021-12-08 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20211208_0421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='apartment',
            new_name='listing',
        ),
    ]
