# Generated by Django 3.2 on 2021-12-09 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_auto_20211208_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_rooms', to='listings.listing'),
        ),
    ]
