# Generated by Django 3.2 on 2021-12-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_alter_hotelroom_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelroom',
            name='hotel',
        ),
    ]
