# Generated by Django 3.2 on 2021-12-10 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_remove_hotelroom_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='listings.listing'),
        ),
    ]
